{{- if and .Release.IsInstall .Values.global.installCRDs -}}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/Alertmanager") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "alertmanagers.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: Alertmanager
    plural: alertmanagers
    listKind: AlertmanagerList
    singular: alertmanager
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "alertmanagerconfigs.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: AlertmanagerConfig
    plural: alertmanagerconfigs
    listKind: AlertmanagerConfigList
    singular: alertmanagerconfig
  scope: Namespaced
  version: v1alpha1
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/Prometheus") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "prometheuses.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: Prometheus
    plural: prometheuses
    listKind: PrometheusList
    singular: prometheus
  scope: Namespaced
  version: v1
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "prometheusrules.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: PrometheusRule
    plural: prometheusrules
    listKind: PrometheusRuleList
    singular: prometheusrule
  scope: Namespaced
  version: v1
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "servicemonitors.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: ServiceMonitor
    plural: servicemonitors
    listKind: ServiceMonitorList
    singular: servicemonitor
  scope: Namespaced
  version: v1
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "podmonitors.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: PodMonitor
    plural: podmonitors
    listKind: PodMonitorList
    singular: podmonitor
  scope: Namespaced
  version: v1
{{- end }}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "probes.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: Probe
    plural: probes
    listKind: ProbeList
    singular: probe
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ printf "thanosrulers.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: ThanosRuler
    plural: thanosrulers
    listKind: ThanosRulerList
    singular: thanosruler
  scope: Namespaced
  version: v1
{{- end -}}